/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lt_neworld_arRegistration_Process */

#ifndef _Included_lt_neworld_arRegistration_Process
#define _Included_lt_neworld_arRegistration_Process
#ifdef __cplusplus
extern "C" {
#endif
#undef lt_neworld_arRegistration_Process_MIN_PRIORITY
#define lt_neworld_arRegistration_Process_MIN_PRIORITY 1L
#undef lt_neworld_arRegistration_Process_NORM_PRIORITY
#define lt_neworld_arRegistration_Process_NORM_PRIORITY 5L
#undef lt_neworld_arRegistration_Process_MAX_PRIORITY
#define lt_neworld_arRegistration_Process_MAX_PRIORITY 10L
#undef lt_neworld_arRegistration_Process_FRAMES_FOR_COUNT
#define lt_neworld_arRegistration_Process_FRAMES_FOR_COUNT 20L
#undef lt_neworld_arRegistration_Process_COLOR_PICKING_AREA
#define lt_neworld_arRegistration_Process_COLOR_PICKING_AREA 16L
#undef lt_neworld_arRegistration_Process_COLOR_TRESHOLD
#define lt_neworld_arRegistration_Process_COLOR_TRESHOLD 10L
/*
 * Class:     lt_neworld_arRegistration_Process
 * Method:    process
 * Signature: ([BIBB)[I
 */
JNIEXPORT jintArray JNICALL Java_lt_neworld_arRegistration_Process_process
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif

#define NULL 0
#define false  0
#define true   1

struct IndexStack {
	int index;
	struct IndexStack *up;
};
